### ISSUE TITLE
Create a deprecation policy document

### ISSUE THREAD

**Issue by incertum** [falcosecurity/.github#115]
Create a formal deprecation policy document in addition to a page on the official Falco website.

@leogr 
```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/falco/pull/2986
```

**Comment by leogr** [comment]
/remove-lifecycle stale

see https://github.com/falcosecurity/falco/pull/2986

**Comment by leogr** [comment]
Since GitHub has no special feature for the _deprecation policy_ (compared to other [community-related docs](https://github.com/falcosecurity/falco/community) like the contribution guide and the security policy), we will not get any benefit to duplicate the content under `falcosecurity/.github`. We should instead link the official policy (once it gets published on the website).

So
/close

Feel free to reopen this if you disagree!
